version: '3'
services:
  backend-server:
    image: "chandukurra183/todo-server"
    hostname: backend-server
    mem_limit: 128m
    restart: always
    environment:
      - NODE_ENV=dev
      - PORT=4000
      - JWT_SECRET=$JWT_SECRET
      - SERVER_HOST=backend-server
      - SESSION_SECRET=$SESSION_SECRET
      - DB_URL=$DB_URL
      - EMAIL=$EMAIL
      - EMAIL_PASSWORD =$EMAIL_PASSWORD
  nginx:
    image: "chandukurra183/todo-nginx"
    hostname: nginx
    mem_limit: 128m
    restart: always
    ports:
      - "80:80"